#!/bin/bash
# Installs Ruby, Ruby Gems, SASS, Compass

apt-get install -y ruby
apt-get install -y ruby-full
apt-get install -y rubygems

sudo cat <<EOF  >> /root/.bashrc
export PATH=$PATH:/var/lib/gems/1.8/bin
EOF

gem install sass
gem install compass
