#!/bin/bash
# Installs MongoDB

mkdir -p /data/db

cd /tmp
wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.1.tgz
tar -xvzf mongodb-linux-x86_64-2.6.1.tgz
mv mongodb-linux-x86_64-2.6.1 /opt/mongodb

# Create Upstart service for gearman manager script.
cat << 'EOF' > /etc/init/mongodb.conf
description "MongoDB"
version "1.0"

start on runlevel [2345]
stop on shutdown

# Automatically Respawn:
respawn
respawn limit 99 5

# configuration variables.

script
/opt/mongodb/bin/mongod >> /var/log/mongodb.log
end script
EOF

# Start Upstart service.
sudo start mongodb

exit 0
