#!/bin/bash
# Installs Node.JS

apt-get install -y python-software-properties
apt-add-repository ppa:chris-lea/node.js
apt-get update
apt-get install -y nodejs

# Various Node libraries to be installed globally

npm install -g grunt-cli
npm install -g compass
npm install -g bower
npm install -g jshint
npm install -g fixmyjs
npm install -g mocha
npm install -g should
npm install -g browserify
npm install -g phantomjs
npm install -g mocha-phantomjs
npm install -g grunt-mocha-phantomjs
npm install -g grunt-lib-phantomjs

exit 0
