#!/bin/bash

rm /etc/nginx/nginx.conf

cat << 'EOF' > /etc/nginx/app-proxy.conf

proxy_redirect off;
proxy_set_header   X-Real-IP            $remote_addr;
proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Proto $scheme;
proxy_set_header   Host                   $http_host;
proxy_set_header   X-NginX-Proxy    true;
proxy_set_header   Connection "";
proxy_http_version 1.1;
proxy_cache one;
proxy_cache_key sfs$request_uri$scheme;
proxy_pass         http://app_upstream;

EOF

cat << 'EOF' > /etc/nginx/nginx.conf

events {
    worker_connections 768;
}

http {

    types_hash_max_size 2048;

    proxy_cache_path  /var/cache/nginx levels=1:2 keys_zone=one:8m max_size=3000m inactive=600m;
    proxy_temp_path /var/tmp;
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    gzip on;
    gzip_comp_level 6;
    gzip_vary on;
    gzip_min_length  1000;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_buffers 16 8k;

    upstream app_upstream {
        server 127.0.0.1:3000;
        keepalive 64;
    }

    server {

        listen 80;
        server_name modernweb.site;
    	index index.html;

        location / {
    	    include /etc/nginx/app-proxy.conf;
        }

    }

}

EOF

rm /etc/nginx/sites-enabled/default

service nginx restart

exit 0
